### ISSUE TITLE
Redirect Loop     Redirection limit for this URL exceeded.  Unable to load the requested page.   

### ISSUE THREAD

**Issue by tablecell** [natzar/Standart#1]
config.php    34
```
	$RELATIVE_PATH = '/';
```
visit  http://localhost

Redirect Loop
Redirection limit for this URL exceeded

**Comment by natzar** [comment]
If you put everything in a folder inside root, and $RELATIVE_PATH = '/subfolder'; , same result?

**Comment by tablecell** [comment]
```
 Standart-master
                \_  index.php
                \_  config.php 
```
Standart-master  is DOCUMENT_ROOT
      config.php  
```
	$RELATIVE_PATH = '/';
          ...
```

**Comment by natzar** [comment]
So, $RELATIVE_PATH = '/Standart-master';

To access it: http://localhost/Standart-master
